name: new_environment
channels:
  - conda-forge
  - defaults
dependencies:
  - python # Ensures the Python interpreter is installed in the environment.
  - beautifulsoup4==4.12.3
  - email-validator==2.1.1
  - flask==3.0.3
  - flask-login==0.6.3
  - flask-sqlalchemy==3.1.1
  - flask-wtf==1.2.1
  - google-generativeai==0.3.2
  - langchain==0.1.13
  - langchain-google-genai==0.0.9
  - psycopg2-binary==2.9.9
  - pyflakes==3.3.2
  - requests==2.31.0
  - sqlalchemy==2.0.28
  - werkzeug==3.0.2
  - wtforms==3.1.2
  - pip
  - pip:
    - gunicorn==23.0.0
